package github.theworksofbh.buildersparadise.datagen;

import github.theworksofbh.buildersparadise.BuildersParadise;
import github.theworksofbh.buildersparadise.items.ModItems;
import github.theworksofbh.buildersparadise.tags.ModItemTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.data.ItemTagsProvider;

import java.util.concurrent.CompletableFuture;

public class ModItemTagsProvider extends ItemTagsProvider {


    public ModItemTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, lookupProvider, BuildersParadise.MODID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(ItemTags.PIGLIN_LOVED).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_DOOR.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_TRAPDOOR.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CUT_GOLD.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CUT_GOLD_SLAB.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CUT_GOLD_STAIRS.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_CHAIN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_BULB.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_GRATE.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_TORCH.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GILDED_BLACKSTONE_STAIRS.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GILDED_BLACKSTONE_SLAB.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GILDED_BLACKSTONE_WALL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GILDED_BLACKSTONE_FENCE.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_LANTERN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_SOUL_LANTERN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.GOLD_FIRE_LANTERN.get()).orElseThrow());
        tag(ModItemTags.CHESTS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.OAK_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SPRUCE_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BIRCH_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.JUNGLE_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.ACACIA_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.DARK_OAK_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CRIMSON_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.WARPED_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.MANGROVE_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CHERRY_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BAMBOO_CHEST.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.PALE_OAK_CHEST.get()).orElseThrow());
        tag(ModItemTags.DROPPERS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.STONE_DROPPER.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BLACKSTONE_DROPPER.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.DEEPSLATE_DROPPER.get()).orElseThrow());
        tag(ModItemTags.CONCRETE).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.white()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.orange()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.magenta()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.lightBlue()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.yellow()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.lime()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.pink()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.gray()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.lightGray()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.cyan()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.purple()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.blue()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.brown()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.green()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.red()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.CONCRETE.black()).orElseThrow());
        tag(ItemTags.BEACON_PAYMENT_ITEMS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SILVER_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.PLATINUM_INGOT.get()).orElseThrow());
        tag(ModItemTags.BRONZE_TOOL_MATERIALS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_INGOT.get()).orElseThrow());
        tag(ModItemTags.REPAIRS_BRONZE_ARMOR).addTag(ModItemTags.BRONZE_TOOL_MATERIALS);
        tag(ModItemTags.BARRELS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.OAK_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SPRUCE_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BIRCH_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.JUNGLE_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.ACACIA_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.DARK_OAK_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CRIMSON_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.WARPED_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.MANGROVE_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CHERRY_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BAMBOO_BARREL.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.PALE_OAK_BARREL.get()).orElseThrow());
        tag(ItemTags.TRIM_MATERIALS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.ZINC_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SILVER_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.TIN_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.TUNGSTEN_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.LEAD_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.PLATINUM_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.URANIUM_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRASS_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.STEEL_INGOT.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SCULK_BRICK.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BISMUTH_INGOT.get()).orElseThrow());
        tag(ItemTags.TRIMMABLE_ARMOR).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_HELMET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_CHESTPLATE.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_LEGGINGS.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_BOOTS.get()).orElseThrow());
        tag(ModItemTags.VIABLE_FLETCHING_INGREDIENTS).add(BuiltInRegistries.ITEM.getResourceKey(Items.FLINT).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.GLOWSTONE_DUST).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.GUNPOWDER).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(Items.PHANTOM_MEMBRANE).orElseThrow());
        tag(ItemTags.ARROWS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.EXPLOSIVE_ARROW.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SHARPENED_ARROW.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.STREAMLINED_ARROW.get()).orElseThrow());
        tag(ItemTags.METAL_NUGGETS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.ZINC_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SILVER_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.TIN_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.TUNGSTEN_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.PLATINUM_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.LEAD_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.URANIUM_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.NETHERITE_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRONZE_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.BRASS_NUGGET.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.STEEL_NUGGET.get()).orElseThrow());
        tag(ItemTags.LOOM_PATTERNS).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.HEART_BANNER_PATTERN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.DIAMOND_BANNER_PATTERN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.SPADE_BANNER_PATTERN.get()).orElseThrow()).add(BuiltInRegistries.ITEM.getResourceKey(ModItems.CLUB_BANNER_PATTERN.get()).orElseThrow());
    }
}
