package github.theworksofbh.buildersparadise.compat.bop.config;

import biomesoplenty.api.item.BOPItems;
import github.theworksofbh.buildersparadise.compat.bop.CompatModItems;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.fml.ModList;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;

public class BOPCreativeInvConfig {
    public static void addModItemsToVanillaTabs(BuildCreativeModeTabContentsEvent tabData) {
        if (tabData.getTabKey().identifier().getNamespace().contains("biomesoplenty") && ModList.get().isLoaded("biomesoplenty")) {
            tabData.remove(BOPItems.WHITE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.WHITE_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_WHITE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CUT_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CHISELED_WHITE_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.BLACK_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.BLACK_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_BLACK_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CUT_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CHISELED_BLACK_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.ORANGE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.ORANGE_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_ORANGE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.SMOOTH_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CUT_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.remove(BOPItems.CHISELED_ORANGE_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.BRIMSTONE_BRICK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BRIMSTONE_BRICK_STAIRS.getDefaultInstance(), BOPItems.BRIMSTONE_BRICK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.BRIMSTONE.getDefaultInstance(), CompatModItems.BRIMSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BRIMSTONE.getDefaultInstance(), CompatModItems.BRIMSTONE_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BRIMSTONE.getDefaultInstance(), CompatModItems.BRIMSTONE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.WHITE_SANDSTONE.getDefaultInstance(), BOPItems.CHISELED_WHITE_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WHITE_SANDSTONE.getDefaultInstance(), BOPItems.WHITE_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WHITE_SANDSTONE.getDefaultInstance(), BOPItems.WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WHITE_SANDSTONE.getDefaultInstance(), BOPItems.WHITE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_WHITE_SANDSTONE.getDefaultInstance(), BOPItems.CUT_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_WHITE_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_WHITE_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_WHITE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.BLACK_SANDSTONE.getDefaultInstance(), BOPItems.CHISELED_BLACK_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BLACK_SANDSTONE.getDefaultInstance(), BOPItems.BLACK_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BLACK_SANDSTONE.getDefaultInstance(), BOPItems.BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BLACK_SANDSTONE.getDefaultInstance(), BOPItems.BLACK_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_BLACK_SANDSTONE.getDefaultInstance(), BOPItems.CUT_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_BLACK_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_BLACK_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_BLACK_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.CHISELED_ORANGE_SANDSTONE.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.ORANGE_SANDSTONE_WALL.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.ORANGE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.CUT_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_ORANGE_SANDSTONE.getDefaultInstance(), BOPItems.SMOOTH_ORANGE_SANDSTONE_STAIRS.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.CUT_WHITE_SANDSTONE.getDefaultInstance(), CompatModItems.CUT_WHITE_SANDSTONE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.CUT_WHITE_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_WHITE_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.SMOOTH_WHITE_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.CUT_BLACK_SANDSTONE.getDefaultInstance(), CompatModItems.CUT_BLACK_SANDSTONE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.CUT_BLACK_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_BLACK_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.SMOOTH_BLACK_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.CUT_ORANGE_SANDSTONE.getDefaultInstance(), CompatModItems.CUT_ORANGE_SANDSTONE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.CUT_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.CUT_ORANGE_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.SMOOTH_ORANGE_SANDSTONE_SLAB.getDefaultInstance(), CompatModItems.SMOOTH_ORANGE_SANDSTONE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_BRICK_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_BRICK_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_BRICK_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_BRICKS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.POLISHED_THERMAL_CALCITE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.POLISHED_THERMAL_CALCITE_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.POLISHED_THERMAL_CALCITE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.POLISHED_THERMAL_CALCITE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_WALL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.THERMAL_CALCITE.getDefaultInstance(), CompatModItems.THERMAL_CALCITE_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.ROSE_QUARTZ_BLOCK.getDefaultInstance(), CompatModItems.CUT_ROSE_QUARTZ_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ROSE_QUARTZ_BLOCK.getDefaultInstance(), CompatModItems.CUT_ROSE_QUARTZ_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ROSE_QUARTZ_BLOCK.getDefaultInstance(), CompatModItems.CUT_ROSE_QUARTZ.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.DEAD_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_STAIRS.getDefaultInstance(), BOPItems.DEAD_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_PLANKS.getDefaultInstance(), CompatModItems.DEAD_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_STAIRS.getDefaultInstance(), CompatModItems.DEAD_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_SLAB.getDefaultInstance(), CompatModItems.DEAD_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_BUTTON.getDefaultInstance(), CompatModItems.DEAD_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_SHELF.getDefaultInstance(), CompatModItems.DEAD_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_HANGING_SIGN.getDefaultInstance(), CompatModItems.DEAD_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_HANGING_SIGN.getDefaultInstance(), CompatModItems.DEAD_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_HANGING_SIGN.getDefaultInstance(), CompatModItems.DEAD_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_HANGING_SIGN.getDefaultInstance(), CompatModItems.DEAD_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.DEAD_HANGING_SIGN.getDefaultInstance(), CompatModItems.DEAD_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.EMPYREAL_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_STAIRS.getDefaultInstance(), BOPItems.EMPYREAL_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_PLANKS.getDefaultInstance(), CompatModItems.EMPYREAL_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_STAIRS.getDefaultInstance(), CompatModItems.EMPYREAL_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_SLAB.getDefaultInstance(), CompatModItems.EMPYREAL_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_BUTTON.getDefaultInstance(), CompatModItems.EMPYREAL_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_SHELF.getDefaultInstance(), CompatModItems.EMPYREAL_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_HANGING_SIGN.getDefaultInstance(), CompatModItems.EMPYREAL_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_HANGING_SIGN.getDefaultInstance(), CompatModItems.EMPYREAL_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_HANGING_SIGN.getDefaultInstance(), CompatModItems.EMPYREAL_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_HANGING_SIGN.getDefaultInstance(), CompatModItems.EMPYREAL_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.EMPYREAL_HANGING_SIGN.getDefaultInstance(), CompatModItems.EMPYREAL_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.FIR_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_STAIRS.getDefaultInstance(), BOPItems.FIR_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_PLANKS.getDefaultInstance(), CompatModItems.FIR_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_STAIRS.getDefaultInstance(), CompatModItems.FIR_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_SLAB.getDefaultInstance(), CompatModItems.FIR_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_BUTTON.getDefaultInstance(), CompatModItems.FIR_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_SHELF.getDefaultInstance(), CompatModItems.FIR_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_HANGING_SIGN.getDefaultInstance(), CompatModItems.FIR_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_HANGING_SIGN.getDefaultInstance(), CompatModItems.FIR_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_HANGING_SIGN.getDefaultInstance(), CompatModItems.FIR_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_HANGING_SIGN.getDefaultInstance(), CompatModItems.FIR_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.FIR_HANGING_SIGN.getDefaultInstance(), CompatModItems.FIR_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.HELLBARK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_STAIRS.getDefaultInstance(), BOPItems.HELLBARK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_PLANKS.getDefaultInstance(), CompatModItems.HELLBARK_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_STAIRS.getDefaultInstance(), CompatModItems.HELLBARK_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_SLAB.getDefaultInstance(), CompatModItems.HELLBARK_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_BUTTON.getDefaultInstance(), CompatModItems.HELLBARK_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_SHELF.getDefaultInstance(), CompatModItems.HELLBARK_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_HANGING_SIGN.getDefaultInstance(), CompatModItems.HELLBARK_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_HANGING_SIGN.getDefaultInstance(), CompatModItems.HELLBARK_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_HANGING_SIGN.getDefaultInstance(), CompatModItems.HELLBARK_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_HANGING_SIGN.getDefaultInstance(), CompatModItems.HELLBARK_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.HELLBARK_HANGING_SIGN.getDefaultInstance(), CompatModItems.HELLBARK_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.JACARANDA_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_STAIRS.getDefaultInstance(), BOPItems.JACARANDA_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_PLANKS.getDefaultInstance(), CompatModItems.JACARANDA_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_STAIRS.getDefaultInstance(), CompatModItems.JACARANDA_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_SLAB.getDefaultInstance(), CompatModItems.JACARANDA_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_BUTTON.getDefaultInstance(), CompatModItems.JACARANDA_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_SHELF.getDefaultInstance(), CompatModItems.JACARANDA_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_HANGING_SIGN.getDefaultInstance(), CompatModItems.JACARANDA_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_HANGING_SIGN.getDefaultInstance(), CompatModItems.JACARANDA_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_HANGING_SIGN.getDefaultInstance(), CompatModItems.JACARANDA_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_HANGING_SIGN.getDefaultInstance(), CompatModItems.JACARANDA_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.JACARANDA_HANGING_SIGN.getDefaultInstance(), CompatModItems.JACARANDA_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.MAGIC_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_STAIRS.getDefaultInstance(), BOPItems.MAGIC_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_PLANKS.getDefaultInstance(), CompatModItems.MAGIC_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_STAIRS.getDefaultInstance(), CompatModItems.MAGIC_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_SLAB.getDefaultInstance(), CompatModItems.MAGIC_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_BUTTON.getDefaultInstance(), CompatModItems.MAGIC_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_SHELF.getDefaultInstance(), CompatModItems.MAGIC_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAGIC_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAGIC_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAGIC_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAGIC_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAGIC_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAGIC_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.MAHOGANY_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_STAIRS.getDefaultInstance(), BOPItems.MAHOGANY_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_PLANKS.getDefaultInstance(), CompatModItems.MAHOGANY_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_STAIRS.getDefaultInstance(), CompatModItems.MAHOGANY_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_SLAB.getDefaultInstance(), CompatModItems.MAHOGANY_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_BUTTON.getDefaultInstance(), CompatModItems.MAHOGANY_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_SHELF.getDefaultInstance(), CompatModItems.MAHOGANY_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAHOGANY_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAHOGANY_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAHOGANY_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAHOGANY_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAHOGANY_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAHOGANY_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.MAPLE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_STAIRS.getDefaultInstance(), BOPItems.MAPLE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_PLANKS.getDefaultInstance(), CompatModItems.MAPLE_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_STAIRS.getDefaultInstance(), CompatModItems.MAPLE_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_SLAB.getDefaultInstance(), CompatModItems.MAPLE_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_BUTTON.getDefaultInstance(), CompatModItems.MAPLE_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_SHELF.getDefaultInstance(), CompatModItems.MAPLE_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAPLE_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAPLE_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAPLE_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAPLE_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.MAPLE_HANGING_SIGN.getDefaultInstance(), CompatModItems.MAPLE_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.PALM_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_STAIRS.getDefaultInstance(), BOPItems.PALM_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_PLANKS.getDefaultInstance(), CompatModItems.PALM_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_STAIRS.getDefaultInstance(), CompatModItems.PALM_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_SLAB.getDefaultInstance(), CompatModItems.PALM_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_BUTTON.getDefaultInstance(), CompatModItems.PALM_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_SHELF.getDefaultInstance(), CompatModItems.PALM_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_HANGING_SIGN.getDefaultInstance(), CompatModItems.PALM_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_HANGING_SIGN.getDefaultInstance(), CompatModItems.PALM_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_HANGING_SIGN.getDefaultInstance(), CompatModItems.PALM_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_HANGING_SIGN.getDefaultInstance(), CompatModItems.PALM_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PALM_HANGING_SIGN.getDefaultInstance(), CompatModItems.PALM_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.PINE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_STAIRS.getDefaultInstance(), BOPItems.PINE_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_PLANKS.getDefaultInstance(), CompatModItems.PINE_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_STAIRS.getDefaultInstance(), CompatModItems.PINE_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_SLAB.getDefaultInstance(), CompatModItems.PINE_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_BUTTON.getDefaultInstance(), CompatModItems.PINE_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_SHELF.getDefaultInstance(), CompatModItems.PINE_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_HANGING_SIGN.getDefaultInstance(), CompatModItems.PINE_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_HANGING_SIGN.getDefaultInstance(), CompatModItems.PINE_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_HANGING_SIGN.getDefaultInstance(), CompatModItems.PINE_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_HANGING_SIGN.getDefaultInstance(), CompatModItems.PINE_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.PINE_HANGING_SIGN.getDefaultInstance(), CompatModItems.PINE_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.REDWOOD_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_STAIRS.getDefaultInstance(), BOPItems.REDWOOD_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_PLANKS.getDefaultInstance(), CompatModItems.REDWOOD_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_STAIRS.getDefaultInstance(), CompatModItems.REDWOOD_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_SLAB.getDefaultInstance(), CompatModItems.REDWOOD_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_BUTTON.getDefaultInstance(), CompatModItems.REDWOOD_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_SHELF.getDefaultInstance(), CompatModItems.REDWOOD_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_HANGING_SIGN.getDefaultInstance(), CompatModItems.REDWOOD_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_HANGING_SIGN.getDefaultInstance(), CompatModItems.REDWOOD_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_HANGING_SIGN.getDefaultInstance(), CompatModItems.REDWOOD_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_HANGING_SIGN.getDefaultInstance(), CompatModItems.REDWOOD_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.REDWOOD_HANGING_SIGN.getDefaultInstance(), CompatModItems.REDWOOD_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.UMBRAN_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_STAIRS.getDefaultInstance(), BOPItems.UMBRAN_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_PLANKS.getDefaultInstance(), CompatModItems.UMBRAN_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_STAIRS.getDefaultInstance(), CompatModItems.UMBRAN_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_SLAB.getDefaultInstance(), CompatModItems.UMBRAN_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_BUTTON.getDefaultInstance(), CompatModItems.UMBRAN_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_SHELF.getDefaultInstance(), CompatModItems.UMBRAN_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_HANGING_SIGN.getDefaultInstance(), CompatModItems.UMBRAN_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_HANGING_SIGN.getDefaultInstance(), CompatModItems.UMBRAN_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_HANGING_SIGN.getDefaultInstance(), CompatModItems.UMBRAN_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_HANGING_SIGN.getDefaultInstance(), CompatModItems.UMBRAN_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.UMBRAN_HANGING_SIGN.getDefaultInstance(), CompatModItems.UMBRAN_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.WILLOW_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_STAIRS.getDefaultInstance(), BOPItems.WILLOW_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_PLANKS.getDefaultInstance(), CompatModItems.WILLOW_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_STAIRS.getDefaultInstance(), CompatModItems.WILLOW_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_SLAB.getDefaultInstance(), CompatModItems.WILLOW_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_CHISELED_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_BEEHIVE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_SOUL_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_CAMPFIRE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_DEEPSLATE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_BLACKSTONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_STONE_SMOKER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_LOOM.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_GRINDSTONE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_SMITHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_FLETCHING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_CARTOGRAPHY_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_BUTTON.getDefaultInstance(), CompatModItems.WILLOW_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_SHELF.getDefaultInstance(), CompatModItems.WILLOW_LECTERN.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_HANGING_SIGN.getDefaultInstance(), CompatModItems.WILLOW_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_HANGING_SIGN.getDefaultInstance(), CompatModItems.WILLOW_CRAFTER.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_HANGING_SIGN.getDefaultInstance(), CompatModItems.WILLOW_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_HANGING_SIGN.getDefaultInstance(), CompatModItems.WILLOW_BARREL.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.WILLOW_HANGING_SIGN.getDefaultInstance(), CompatModItems.WILLOW_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.remove(BOPItems.ORIGIN_OAK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_STAIRS.getDefaultInstance(), BOPItems.ORIGIN_OAK_SLAB.getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_PLANKS.getDefaultInstance(), CompatModItems.ORIGIN_OAK_MOSAIC.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_STAIRS.getDefaultInstance(), CompatModItems.ORIGIN_OAK_MOSAIC_STAIRS.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_SLAB.getDefaultInstance(), CompatModItems.ORIGIN_OAK_MOSAIC_SLAB.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_BUTTON.getDefaultInstance(), CompatModItems.ORIGIN_OAK_BOOKSHELF.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_BUTTON.getDefaultInstance(), CompatModItems.ORIGIN_OAK_CRAFTING_TABLE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_HANGING_SIGN.getDefaultInstance(), CompatModItems.ORIGIN_OAK_CHEST_MINECART.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_HANGING_SIGN.getDefaultInstance(), CompatModItems.ORIGIN_OAK_TRAPPED_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.ORIGIN_OAK_HANGING_SIGN.getDefaultInstance(), CompatModItems.ORIGIN_OAK_CHEST.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.WHITE_SANDSTONE_WALL.getDefaultInstance(), CompatModItems.WHITE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.CUT_WHITE_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.CUT_WHITE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.SMOOTH_WHITE_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.SMOOTH_WHITE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.BLACK_SANDSTONE_WALL.getDefaultInstance(), CompatModItems.BLACK_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.CUT_BLACK_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.CUT_BLACK_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.SMOOTH_BLACK_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.SMOOTH_BLACK_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(BOPItems.ORANGE_SANDSTONE_WALL.getDefaultInstance(), CompatModItems.ORANGE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.CUT_ORANGE_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.CUT_ORANGE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.SMOOTH_ORANGE_SANDSTONE_WALL.get().getDefaultInstance(), CompatModItems.SMOOTH_ORANGE_SANDSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(CompatModItems.BRIMSTONE_WALL.get().getDefaultInstance(), CompatModItems.BRIMSTONE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(BOPItems.BRIMSTONE_BRICK_WALL.getDefaultInstance(), CompatModItems.BRIMSTONE_BRICK_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.insertAfter(CompatModItems.THERMAL_CALCITE_WALL.get().getDefaultInstance(), CompatModItems.THERMAL_CALCITE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.POLISHED_THERMAL_CALCITE_WALL.get().getDefaultInstance(), CompatModItems.POLISHED_THERMAL_CALCITE_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.insertAfter(CompatModItems.THERMAL_CALCITE_BRICK_WALL.get().getDefaultInstance(), CompatModItems.THERMAL_CALCITE_BRICK_FENCE.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);

            tabData.accept(CompatModItems.WHITE_SANDSTONE_BATON.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.accept(CompatModItems.BLACK_SANDSTONE_BATON.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.accept(CompatModItems.ORANGE_SANDSTONE_BATON.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
            tabData.accept(CompatModItems.BRIMSTONE_BATON.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);


        }
    }

}
